name: Testing expertise

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Frontend

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14.18.0
        cache: "npm"
    
    - run: npm install
    - run: npm run build --if-present
      env:
         CI: false

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
          install: true
          working-directory: ./Frontend
          start: npm start 
          wait-on: 'http://localhost:3000'
     
    - name: run contract tests
      run: npm run test:pact


    - name: Run stryker test
      run: npm run test:stryker

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
