name: Testing expertise

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Frontend

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.13.0
        cache: "npm"
        cache-dependency-path: ./Frontend/package-lock.json

      working-directory: ./Server
      run: npm i
      run: npm start

      working-directory: ./Frontend
      run: npm run build --if-present
      run: npm i
    - name: run contract tests
      run: test:pact
      run: yarn cypress:run
    - name: Run stryker test
      run: npm run test:stryker
    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
